### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by ghost** [idlesign/calibre-bookradar#2]
calibre, version 2.41.0
ОШИБКА: Необработанное прерывание:: <b>ImportError</b>:No module named requests

calibre 2.41  isfrozen: True is64bit: True
Linux-3.19.0-31-generic-x86_64-with-debian-jessie-sid Linux ('64bit', 'ELF')
('Linux', '3.19.0-31-generic', '#36-Ubuntu SMP Wed Oct 7 15:04:02 UTC 2015')
Python 2.7.9
Linux: ('debian', 'jessie/sid', '')
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 316, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 388, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 53, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 195, in load
  File "site-packages/calibre/customize/zipplugin.py", line 179, in load_module
  File "calibre_plugins.dummy1.**init**", line 2, in <module>
ImportError: No module named requests

**Comment by idlesign** [comment]
Для работы требуются установленные 
- Calibre
- requests
- BeautifulSoup

В вашем случае не найден пакет requests. Можно попробовать поставить:

> sudo apt-get install python-requests

**Comment by idlesign** [comment]
Закрываю.
